### ISSUE TITLE
Add monitoring support

### ISSUE THREAD

**Issue by nyilmaz** [Polymer/prpl-server#101]
Hi there!

As a CNCF tool, prometheus can be added to monitor typical node.js and express endpoint metrics.

**Comment by aomarks** [comment]
Thanks for the PR, but I think this is a quite specific monitoring integration, so I'm not sure it makes sense to have in this general purpose server. I'd suggest using prpl-server as a library (https://github.com/Polymer/prpl-server#as-a-library), and adding your own middleware that way.

Also note that we're not developing prpl-server any further, so apart from important bug/security fixes, we're not going to be adding any new features.

Since all modern browsers now support all of the features in our capabilities table, there isn't really any benefit to the granular degree of sniffing that prpl-server does. Most apps can now do fine with just two builds: one for modern browsers, and one for IE, and those can be differentiated on the client-side using the `nomodule` script attribute. See https://jasonformat.com/modern-script-loading/ for details.

Chrome is removing HTTP/2 Server Push (https://groups.google.com/a/chromium.org/g/blink-dev/c/K3rYLvmQUBY/m/vOWBKZGoAQAJ?pli=1), so the push support in prpl-server will also no longer provide any benefit.
