### ISSUE TITLE
Support for Firebase Hosting + Cloud Functions

### ISSUE THREAD

**Issue by JosefJezek** [Polymer/prpl-server#44]
Could you add support for Firebase Hosting + Cloud Functions?

Serve Dynamic Content with Cloud Functions
https://firebase.google.com/docs/hosting/functions

Node.js apps on Firebase Hosting Crash Course - Firecasts
https://www.youtube.com/watch?v=LOeioOKUKI8

**Comment by aomarks** [comment]
Yep, we've been planning on working on this. Will update this issue with progress.

**Comment by Brian-McBride** [comment]
Am I wrong, or would this be as simple as configuring the build directories to be firebase hosting directories (and you'll upload your build files there). 
And then setting up a function to take that express endpoint? 
At first glance, I'm not seeing anything that needs state between http requests. Or is there something more complicated?

**Comment by Scarygami** [comment]
I've actually started working on differential serving from Firebase before I realized this issue was here, which resulted in [this article](https://medium.com/@scarygami/differential-serving-on-firebase-hosting-f83c33b83a8e) and a [sample based on polymer-starter-kit](https://github.com/Scarygami/polymer-starter-kit-firebase-hosting). Far from perfect but it works good enough for me so far :)

The biggest problem is that Firebase Hosting and Cloud Functions run in different environments, so you can't simply `send` files from Hosting via functions.

**Comment by JosefJezek** [comment]
@aomarks any progress?

**Comment by abdonrd** [comment]
Friendly ping to @aomarks.

I have also seen interest in this giving a couple of talks about prpl-server, since GAE with Node is not very cheap.

**Comment by JosefJezek** [comment]
@aomarks any progress? Thank you...

**Comment by aomarks** [comment]
Closing because prpl-server is now in maintenance mode. See https://github.com/Polymer/prpl-server#prpl-server for our recently added maintenance mode notice, and recommendations for alternatives.
