### ISSUE TITLE
Example Polymer App Project with prpl-server-node

### ISSUE THREAD

**Issue by Brian-McBride** [Polymer/prpl-server#45]
I'm looking for an example project that implements this - ideally with the Polymer Starter App.

**Comment by CaptainCodeman** [comment]
This PSK but also my Go version instead of node: https://github.com/CaptainCodeman/prpl-server-example

There's really nothing to change for the PSK side of things, as long as you set the `basePath` options for the `polymer.json` build settings. The instructions for serving with node should be as per this projects readme.

**Comment by scenaristeur** [comment]
I've created https://spoggy.netlify.com/ which uses prpl-server
with this tuto : https://polymer.github.io/pwa-starter-kit/setup/ 
github -> https://github.com/scenaristeur/spoggy3

**Comment by aomarks** [comment]
Closing because prpl-server is now in maintenance mode. See https://github.com/Polymer/prpl-server#prpl-server for our recently added maintenance mode notice, and recommendations for alternatives.
