### ISSUE TITLE
Allow serving builds based on browser versions

### ISSUE THREAD

**Issue by Dabolus** [Polymer/prpl-server#82]
I know that this feature might require some work, but it would be great to have the possibility to pass a [`browserslist`](https://github.com/browserslist/browserslist) config instead of using `browserCapabilities`. This would allow to use PRPL server more easily with tools other than the Polymer CLI, as `browserslist` is used by lots of libraries (e.g. Babel and PostCSS) and would be easily usable with other build tools.

**Comment by Dabolus** [comment]
I also discovered [this library](https://github.com/browserslist/browserslist-useragent) that might eventually be useful to implement this behavior.

**Comment by aomarks** [comment]
Thank you for the feature request. Closing because we are no longer accepting new feature requests for prpl-server.

See https://github.com/Polymer/prpl-server#prpl-server for our recently added maintenance mode notice, and recommendations for alternatives. In particular, you may be interested in the new advice we have there for differential serving.
